apiVersion: v1
kind: Service
metadata:
  name: hello-world
  labels:
    app: hello-world
spec:
  type: NodePort
  externalIPs:
    - 192.168.50.2
  ports:
    - port: 3000
      targetPort: 8000
      protocol: TCP
  selector:
    app: hello-world
---
apiVersion: extensions/v1beta1
kind: Deployment
metadata:
  name: hello-world-deployment
spec:
  replicas: 2
  template:
    metadata:
      labels:
        app: hello-world
    spec:
      containers:
      - name: hello-world
        image: 192.168.50.2:5000/sample/hello-world:1
        ports:
        - containerPort: 8000
